apiVersion: v1
kind: Pod
metadata: 
  name: sample-pod
  labels:
    app: sample
    owner: bueno
    mylabel: i_am_a_label
    version: v1.0.0

spec:
  containers:
    - name: nginx-server
      image: nginx
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"