apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-rc
  labels:
    owner: bueno
    mylabel: i_am_a_label
    version: v1.0.0

spec:
  replicas: 2

  selector:
    app: sample

  template:
    metadata:
      name: sample-rc-pod
      labels:
        app: sample
        owner: bueno
        mylabel: i_am_another_label
        version: v2.0.0
    spec:
      containers:
      - name: nginx-server
        image: nginx
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
